# coding: utf-8

"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    OpenAPI spec version: 2021-07-12

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.approver import Approver  # noqa: E501
from swagger_client.rest import ApiException


class TestApprover(unittest.TestCase):
    """Approver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApprover(self):
        """Test Approver"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.approver.Approver()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
