"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-07-28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import generated
from generated.model.cause import Cause


class TestCause(unittest.TestCase):
    """Cause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCause(self):
        """Test Cause"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Cause()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
