# coding: utf-8

"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    OpenAPI spec version: 2021-07-07

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_campaigns_get(self):
        """Test case for campaigns_get

        Returns a list of campaigns  # noqa: E501
        """
        pass

    def test_campaigns_id_get(self):
        """Test case for campaigns_id_get

        returns a single of campaign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
