# coding: utf-8

"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    OpenAPI spec version: 2021-07-07
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.campaign import Campaign  # noqa: E501
from swagger_client.rest import ApiException


class TestCampaign(unittest.TestCase):
    """Campaign unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaign(self):
        """Test Campaign"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.campaign.Campaign()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
