"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    The version of the OpenAPI document: 2021-07-28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import generated
from generated.model.approver import Approver


class TestApprover(unittest.TestCase):
    """Approver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApprover(self):
        """Test Approver"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Approver()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
