# coding: utf-8

"""
    Emblem API

    REST API for any Emblem server  # noqa: E501

    OpenAPI spec version: 2021-07-07

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.donation import Donation  # noqa: E501
from swagger_client.rest import ApiException


class TestDonation(unittest.TestCase):
    """Donation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDonation(self):
        """Test Donation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.donation.Donation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
