# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - echo
      - '${_BODY}'

  # Cloud Run Deploy
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE_NAME}
      - --region=${_REGION}
      - --platform=managed
      - --revision-suffix=${_REVISION}
      - --project=${_TARGET_PROJECT}
      - --allow-unauthenticated
      - --service-account=cloud-run-manager@${_TARGET_PROJECT}.iam.gserviceaccount.com
      - --no-traffic

  # Send message to pub/sub to start canary rollout process
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - pubsub
      - topics
      - publish
      - canary
      - --message={'_SERVICE':'${_SERVICE}','_REVISION':'${_REVISION}', '_REGION':'${_REGION}', '_TRAFFIC':'5'}
      - --project=${_TARGET_PROJECT}
