# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


steps:
  # Docker Build 
  # Copying the client-libs for Docker context
  - name: gcr.io/cloud-builders/docker
    env:
      - '_REGION=$_REGION'
      - '_PROJECT_ID=$_PROJECT_ID'
      - '_IMAGE_TAG=$_IMAGE_TAG'
    script: |
      #!/usr/bin/env bash
      cp -R client-libs/ website/client-libs
      docker build -t \
      ${_REGION}-docker.pkg.dev/${PROJECT_ID}/website/website:${_IMAGE_TAG} \
      website/. 

# Default to us-central1 
substitutions:
  _REGION: us-central1
  _IMAGE_TAG: $SHORT_SHA

# Store in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/website/website:${_IMAGE_TAG}'
