on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
name: style-terraform
jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - name: Terraform Fmt
        run: terraform fmt --recursive
      - uses: googleapis/code-suggester@v1 # takes the changes from git directory
        with:
          command: review
          pull_number: ${{ github.event.pull_request.number }}
          git_dir: '.'
